# Form implementation generated from reading ui file 'facturation_ci/ui/invoice.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InvoicePage(object):
    def setupUi(self, InvoicePage):
        InvoicePage.setObjectName("InvoicePage")
        InvoicePage.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(InvoicePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_button = QtWidgets.QPushButton(parent=InvoicePage)
        self.new_button.setObjectName("new_button")
        self.horizontalLayout.addWidget(self.new_button)
        self.edit_button = QtWidgets.QPushButton(parent=InvoicePage)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout.addWidget(self.edit_button)
        self.delete_button = QtWidgets.QPushButton(parent=InvoicePage)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.print_button = QtWidgets.QPushButton(parent=InvoicePage)
        self.print_button.setObjectName("print_button")
        self.horizontalLayout.addWidget(self.print_button)
        self.certify_button = QtWidgets.QPushButton(parent=InvoicePage)
        self.certify_button.setObjectName("certify_button")
        self.horizontalLayout.addWidget(self.certify_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_view = QtWidgets.QTableView(parent=InvoicePage)
        self.table_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_view.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_view.setObjectName("table_view")
        self.table_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_view)

        self.retranslateUi(InvoicePage)
        QtCore.QMetaObject.connectSlotsByName(InvoicePage)

    def retranslateUi(self, InvoicePage):
        _translate = QtCore.QCoreApplication.translate
        InvoicePage.setWindowTitle(_translate("InvoicePage", "Gestion des Factures"))
        self.new_button.setText(_translate("InvoicePage", "Nouvelle Facture"))
        self.edit_button.setText(_translate("InvoicePage", "Modifier Facture"))
        self.delete_button.setText(_translate("InvoicePage", "Supprimer Facture"))
        self.print_button.setText(_translate("InvoicePage", "Imprimer"))
        self.certify_button.setText(_translate("InvoicePage", "Certifier (FNE)"))
